name: Build C Multi-Platform

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install GLUT (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y freeglut3-dev

    - name: Install GLUT (Windows)
      if: matrix.os == 'windows-latest'
      run: vcpkg install freeglut:x64-windows

    - name: Compile (Windows)
      if: matrix.os == 'windows-latest'
      run: gcc main.c -o main-windows.exe -IC:/vcpkg/installed/x64-windows/include -LC:/vcpkg/installed/x64-windows/lib -lfreeglut -lopengl32 -lglu32

    - name: Copy GLUT DLL (Windows)
      if: matrix.os == 'windows-latest'
      run: copy C:\vcpkg\installed\x64-windows\bin\freeglut.dll freeglut.dll

    - name: Compile (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: gcc main.c -o main-linux -lGL -lGLU -lglut

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executabile-${{ matrix.os }}
        path: |
          main-windows.exe
          main-linux
          freeglut.dll